openapi: 3.0.0
info:
  title: Vulnerability Testing API
  version: 1.0.0
paths:
  /sql-injection:
    post:
      summary: Test for SQL injection vulnerability
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
