openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /sql-injection:
    post:
      summary: Test for SQL injection vulnerability
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Successful
        '400':
          description: Bad Request
